### ISSUE TITLE
'parmdb' object has no attribute 'addValuesGrid'

### ISSUE THREAD

**Issue by mooneyse** [lmorabit/long_baseline_pipeline#4]
The pipeline crashes at this point:
https://github.com/lmorabit/long_baseline_pipeline/blob/45914063edee7fc155f2902476d7f10bf6fa0484/bin/copySTgains_toCS.py#L85
It states that `'parmdb' object has no attribute 'addValuesGrid'`.

I had a look at the `parmdb` help file:
```
from lofar import parmdb
help(parmdb)
```

There is no `addValuesGrid` function, but there is a `getValuesGrid` function. Is this what it should be? I'm not 100% sure. (There is also an `addValues` function.)

**Comment by tikk3r** [comment]
For me, it seems to work when replacing `addValuesGrid` with just `addValues`. I ran into the same issue when trying to run the pipeline (feb 2017 LOFAR software). After contact with Leah and Astron it seems like they've switched to `addValuesGrid` in the past and apparently back to `addValues` again later. It is confusing, since there is still `getValuesGrid`.
I haven't seen any more replies from Astron's side, but maybe Leah knows more by now.

Frits

**Comment by mooneyse** [comment]
Cool, I'll change it to `addValues` then, thanks.

**Comment by mooneyse** [comment]
If it works, the script should be changed to try addValuesGrid else
addValues, but I'll wait until it can be confirmed that the functions are
identical.

**Comment by lmorabit** [comment]
They are identical. This is a super annoying "feature" of the LOFAR software, and we should try to accommodate people who may be using different versions.
