### ISSUE TITLE
plots of solutions from test fields

### ISSUE THREAD

**Issue by lmorabit** [lmorabit/long_baseline_pipeline#51]
Please attach your images.

**Comment by mooneyse** [comment]
# Solutions for P134+17

## Loop 3 calibrator images
Colour scale goes from -20 mJy/beam to 200 mJy/beam.
![ds9](https://user-images.githubusercontent.com/20988307/67767454-88ba2280-fa48-11e9-8b13-6ea62fe07c80.png)

## Calibrator S3338
* Total flux =
* Distance to phase centre = 1.6 degrees
![S3338_L723586_phasecal MS_freq143675231 93359375](https://user-images.githubusercontent.com/20988307/67764615-442b8880-fa42-11e9-8dd1-a76db082c131.png)

## Calibrator S6850
* Total flux =
* Distance to phase centre = 0 degrees
![S6850_L723586_phasecal MS_freq143675231 93359375](https://user-images.githubusercontent.com/20988307/67764616-442b8880-fa42-11e9-8e3b-d2fba329d43c.png)

## Calibrator S7386
* Total flux =
* Distance to phase centre = 0.4 degrees
![S7386_L723586_phasecal MS_freq143675231 93359375](https://user-images.githubusercontent.com/20988307/67764617-442b8880-fa42-11e9-8ea9-f9f0e453a650.png)

## Calibrator S7408
* Total flux =
* Distance to phase centre = 0.3 degrees
![S7408_L723586_phasecal MS_freq143675231 93359375](https://user-images.githubusercontent.com/20988307/67764618-442b8880-fa42-11e9-9648-dfef0ac30407.png)

## Calibrator S7781
* Total flux =
* Distance to phase centre = 0.7 degrees
![S7781_L723586_phasecal MS_freq143675231 93359375](https://user-images.githubusercontent.com/20988307/67764619-44c41f00-fa42-11e9-93ea-9121048eb815.png)

## Details
* h5parms available [here.](https://drive.google.com/drive/folders/1ZSyNgXbspOFuE4WMwGpjQn5tmTxTzjUB?usp=sharing)
* All stations are there except DE609.
* The observation is 4h long.
* Data > 168 MHz was removed. Other than that, the full bandwidth was used.

**Comment by tikk3r** [comment]
**Field:** Lockman Hole
**Duration:** 8 hours
**Notes:** DE609 excluded, excluded LoTSS extended sources as calibrators. Most solutions look crap, not sure why. Maybe because of their distance?

**LBC overview**
![lbcs_plot_lockman](https://user-images.githubusercontent.com/2464769/68194122-ba853900-ffb4-11e9-8994-5dbca6ed808a.png)
**SL333868**
![SL333868_phasecal MS_tec_freq143992614 74609375](https://user-images.githubusercontent.com/2464769/68193975-6ed28f80-ffb4-11e9-91fb-ae2501b13fd6.png)
**SL333872**
![SL333872_phasecal MS_tec_freq143992614 74609375](https://user-images.githubusercontent.com/2464769/68193979-6f6b2600-ffb4-11e9-8a8a-623942b26c9a.png)
**SL333880**
![SL333880_phasecal MS_tec_freq143992614 74609375](https://user-images.githubusercontent.com/2464769/68193980-6f6b2600-ffb4-11e9-8bff-f8fcf9b810e6.png)
**SL333890**
![SL333890_phasecal MS_tec_freq143992614 74609375](https://user-images.githubusercontent.com/2464769/68193981-6f6b2600-ffb4-11e9-8b37-f1b08771b2cc.png)
**SL334040**
![SL334040_phasecal MS_tec_freq143992614 74609375](https://user-images.githubusercontent.com/2464769/68193984-7003bc80-ffb4-11e9-9e6f-2b1247e4f58e.png)
**SL334042**
![SL334042_phasecal MS_tec_freq143992614 74609375](https://user-images.githubusercontent.com/2464769/68193985-7003bc80-ffb4-11e9-9908-182d5c3bde84.png)
**SL334044**
![SL334044_phasecal MS_tec_freq143992614 74609375](https://user-images.githubusercontent.com/2464769/68193986-7003bc80-ffb4-11e9-966c-21a70348090f.png)
**SL334048**
![SL334048_phasecal MS_tec_freq143992614 74609375](https://user-images.githubusercontent.com/2464769/68193987-709c5300-ffb4-11e9-8b2c-15463d90059a.png)
**SL337424**
![SL337424_phasecal MS_tec_freq143992614 74609375](https://user-images.githubusercontent.com/2464769/68193988-709c5300-ffb4-11e9-9d5f-053bc263621d.png)

**Comment by nealjackson** [comment]
**Field:** MG0751+2716 (reduced by Deepika Venkattu)

![lbcs_plot](https://user-images.githubusercontent.com/9417703/68200736-5e241880-ffb8-11e9-997e-4b8bacc9d440.png)

**SL588355**

![SL588355_L639741_phasecal MS_freq147581481 934](https://user-images.githubusercontent.com/9417703/68200874-a17e8700-ffb8-11e9-819c-98b463cad938.png)
![SL588355_L639741_phasecal apply_tec_output](https://user-images.githubusercontent.com/9417703/68200880-a5120e00-ffb8-11e9-9475-2376bb7c6bda.jpg)

**SL588369**

![SL588369_L639741_phasecal MS_freq147581481 934](https://user-images.githubusercontent.com/9417703/68201167-28cbfa80-ffb9-11e9-85f5-2c8adf6599bd.png)

![SL588369_L639741_phasecal apply_tec_output](https://user-images.githubusercontent.com/9417703/68201143-1a7dde80-ffb9-11e9-916e-a237e0c7d7ad.jpg)

**Comment by jcroston** [comment]
Oops, failed to spot this thread earlier...
Field is LoTSS P024+39 (24.1234,+38.6639)

In order of distance from the pointing centre (none of them are very close):

**L643639**, distance to ctr = 1.4 deg
![S8707_L643639_phasecal MS_freq143675231 934](https://user-images.githubusercontent.com/31618491/68551887-23cbd880-0409-11ea-938c-0f2f07ca642c.png)
![S8707_L643639_phasecal apply_tec_output](https://user-images.githubusercontent.com/31618491/68551890-2cbcaa00-0409-11ea-9d44-a16c953bca2b.png)

**L271687**, distance to ctr = 1.6 deg
![S9583_L643639_phasecal MS_freq143675231 934](https://user-images.githubusercontent.com/31618491/68551918-70afaf00-0409-11ea-9e52-4b34ea56aed8.png)
![S9583_L643639_phasecal apply_tec_output](https://user-images.githubusercontent.com/31618491/68551919-74dbcc80-0409-11ea-9824-4f5c0a850d21.png)

**L271651**, distance to ctr = 1.7 deg
![S10232_L643639_phasecal MS_freq143675231 934](https://user-images.githubusercontent.com/31618491/68551930-8c1aba00-0409-11ea-9d3f-48aec20099cd.png)
![S10232_L643639_phasecal apply_tec_output](https://user-images.githubusercontent.com/31618491/68551933-9046d780-0409-11ea-868a-a35de56e9010.png)

**L324110**, distance to ctr = 1.9 deg
![S3797_L643639_phasecal MS_freq143675231 934](https://user-images.githubusercontent.com/31618491/68551936-a18fe400-0409-11ea-8bae-1f975f730e82.png)
![S3797_L643639_phasecal apply_tec_output2](https://user-images.githubusercontent.com/31618491/68552058-dc464c00-040a-11ea-96c1-b24d30939f14.png)

**Comment by nealjackson** [comment]
Further comment on the MG0751 field (calibrator L588369 above):

The TEC solutions appear perfectly sensible, but the phase plot on the calibrated data looks puzzling (nb frequency is on x and time is y):

![phase_cal](https://user-images.githubusercontent.com/9417703/71262817-7e295480-2338-11ea-8238-49537e5d9e72.png)

There are gradients on some antennas (e.g. PL610, PL611) which don't look just like dispersive delay to me. Any way that these could have got in?

The raw data doesn't look too weird (frequency is y axis here):

![phase_uncal](https://user-images.githubusercontent.com/9417703/71262906-b6309780-2338-11ea-8518-4c41463e3858.png)

The overall map looks very good, but has a noise about 2-3x what would be expected (not surprisingly, as imaging this stuff will cause decorrelation).

**Comment by tikk3r** [comment]
> There are gradients on some antennas (e.g. PL610, PL611) which don't look just like dispersive delay to me. Any way that these could have got in?

What is the scale of those leftover fluctuations? It could be a number of things I guess, but they do see a leftover residual in LoTSS as well that seems to be neither clock nor TEC, from what I've heard. Maybe it's related.

**Comment by lmorabit** [comment]
selfcal changed.
