### ISSUE TITLE
No output in log from download_cats step

### ISSUE THREAD

**Issue by tikk3r** [lmorabit/long_baseline_pipeline#67]
Mostly a small cosmetic issue. The pipeline will crash if there is no LoTSS coverage and no manual catalog is provided. I think this is proper behaviour, but there is no output from `download_cats` in the logs making the problem a bit vague to track down.

I guess genericpipeline eats the `print`s and they should be changed to `logging.info` or `logging.warn`? (I see some logging statements in there already)

The pipeline will crash at `prep_delay_dir` with
```
Beginning step prep_delay_dir
*******************************************
Failed pipeline run: Delay-Calibration
Detailed exception information:
<type 'exceptions.IOError'>
[Errno 2] No such file or directory: '/net/nieuwerijn/data2/rtimmerman/A1795_HBA/A1795/Delay-Calibration/results/best_delay_calibrators.csv'
*******************************************
LOFAR Pipeline finished unsuccesfully.
recipe genericpipeline completed with errors
```

Further up at the offending step there is only
```
2020-07-15 15:06:38 INFO    genericpipeline: Beginning step download_cats
2020-07-15 15:06:40 INFO    genericpipeline: Beginning step ndppp_prep_target
```
while if I run the script separately I see the actual output
```
Attempting to find or download LBCS catalogue.
lbcs_catalogue.csv
DOWNLOADING LBCS Skymodel for the target field
6
Attempting to find or download LoTSS catalogue.
DOWNLOADING LOTSS Skymodel for the target field
Target field not in LoTSS coverage yet! Only writing delay_calibrators.csv
```

**Comment by nealjackson** [comment]
Yes - I made a handmade best_delay_calibrators.csv file to get around a crash in prep_delay_dir:

Observation,RA_LBCS,DEC_LBCS,Date,Time,Goodness,Flags,FT_Goodness,Quality,FT_total,Source_id,RA_LOTSS,DEC_LOTSS,Total_flux,Peak_flux,Major,Minor,PA,DC_Maj,DC_Min,DC_PA,LGZ_Size,LGZ_Width,LGZ_PA,Isl_rms,Resolved,Radius,Select_stat
L465494,237.00275,31.387361,2016-04-26,00:39:06,PPPPPPPPX----,O,576694951----,20.0,5.777777777777778,ILTJ154800.66+312314.5,237.00275,31.387361,490.113543492232,489.435339270786,,,70.001673014535,4.970187003537,3.05031080718564,70.0016730145338,,,,0.195485437870957,U,0.3627791892528577,0.0067263785726493506

with a flux fixed up from NED. You may also need an image_catalogue.csv later on in Split-Directions which should contain the LGZ_Size field for determining map sizes e.g. mine is

Source_id,LBCS_ID,LBCS_RA,LBCS_DEC,RA,DEC,Delta_Position,Total_flux,Peak_flux,peak_to_total,Isl_rms,Resolved,LGZ_Size
ILTJ154912.59+304715.1,L465478,237.302458,30.787528,237.302458,30.787528,0.0,1.0,1.0,1.0,1.0,R,10.0
ILTJ154800.66+312314.5,L465494,237.002750,31.387361,237.002750,31.387361,0.0,1.0,1.0,1.0,1.0,R,10.0

in order to split the LBCS calibrator and target.

**Comment by lmorabit** [comment]
I can change the prints into logging info, but this is also described in
the documentation.

**Comment by tikk3r** [comment]
True, it's completely expected and normal behavour, but it may be good to have a traceable error or warning.

**Comment by lmorabit** [comment]
download_cats has completely changed. please submit a new issue if you run into problems.
