### ISSUE TITLE
aoflagger doesn not open a file due to too many open files

### ISSUE THREAD

**Issue by cyriltasse** [lmorabit/long_baseline_pipeline#88]
I get this other error even when I use `max_per_node = 1`:

```
2023-04-07 13:32:16 WARNING node.nancep7.obs-nancay.fr.executable_args.L402155_SB243_uv.dppp.ms_concat_0: /opt/lofar/aoflagger/bin/aoflagger stderr: An unhandled exception occured: FiledesIO: file /data/levangelista/LOFAR_VLBI_PIPELINE/RUN_DIR/Pre-Facet-Calibrator/L402155_SB134_uv.dppp.ndppp_prep_cal/table.f0 could not be opened: Too many open files
If you think this is a bug, please contact offringa@gmail.com

2023-04-07 13:32:18 ERROR   node.nancep7.obs-nancay.fr.executable_args: Command '/opt/lofar/aoflagger/bin/aoflagger' returned non-zero exit status 30
```

I searched a bit for the `FiledesIO`exception, and saw that it comes from casacore [here](https://casacore.github.io/casacore/classcasacore_1_1FiledesIO.html)

Worth noting - could be connected, is that when I start singularity it warns 

```
WARNING - software has been build with -march=x86-64 but current machine reports -march=cascadelake.
If you encounter strange behaviour or Illegal instruction warnings, consider building a container with the appropriate architecture set.
WARNING - software has been build with -mtune=generic but current machine -mtune=cascadelake.
If you encounter strange behaviour or Illegal instruction warnings, consider building a container with the appropriate architecture set.
```

Could it be related? Have you encountered this issue before?

**Comment by tikk3r** [comment]
We have seen the first error in the past. This was usually related due to some user limit settings. If you're on a bash shell you can run `ulimit -a` and check the entry for "open files". I've usually run into this error when that number is set low like 1024. 

If so, I would try to increase that limit. I've found 4096 is usually what I'm allowed to set it to without special powers. A `ulimit -n 4096` should do the trick to avoid this I think.

The second warning is safe to ignore for the generic containers.

**Comment by cyriltasse** [comment]
That does the trick - thanks!!!
